
# Site settings

url: "https://SBhat35.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"

baseurl: 

# Google tracking id to track your visitors

google-tracking-id: "UA-111421888-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

# Sections shown in the index page

pages_list:
  About: 'about'
  Timeline: 'timeline'
  Skills: 'skills'
  Contact: 'contact'

#############
# HTML Head #
#############

author: "Sachit Bhat"
lang: "en"
title: "Sachit Bhat"
description: "Sachit Bhat's Personal Website"
keywords: "sachit, bhat, vanderbilt"
favicon: "/img/letter.ico"

##########
# Header #
##########

# black-favicon: ""
# me-img: "/img/newprog.png"

background-type: "color-gradient"		# It can be either image, 3d-lines or color-gradient.

# The following configurations are common for both color-gradient and 3d-lines.

background-color-shuffle: True	# Keep shuffle True to get different background everytime.
background-colors:	# You must add at least 4 colors.
  - color: "1021d3"
  - color: "0707b7"
  - color: "071482"
  - color: "070c3a"

  - color: "391577"
  - color: "3f0f91"
  - color: "5717c4"
  - color: "773ed8"
  
  - color: "315bd8"
  - color: "3989dd"
  - color: "3989dd"
  - color: "3989dd"
  
  - color: "5bcbea"
  - color: "1391c6"
  - color: "126cc6"
  - color: "1120c4"

background-color-trasition-speed: 0.001
background-color-update-interval: 0.001

# 3d-lines configuration

# background-lines-color: "b2ebf2"
# background-particles: 300

# static background image

# background-img: ""

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: False # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 4
start-delay: 500
delete-delay: 2000
lines: # You can add HTML tags in the Text
  - text: "Who am I?"
  - text: "Sachit Bhat:"
  - text: "Programmer"
  - text: "Innovator"
  - text: "Pianist"
  - text: "Sports Enthusiast"
  - text: "Foodie"

me-img: "https://github.com/SBhat35.png?size=500"


########
# Blog #
########

post-preview-words: 96

paginate: 5

fb-share: True
twitter-share: True
reddit-share: True
google-plus-share: True
linkedin-share: True
pinterest-share: True
vkontakte-share: True
disqus-shortname: "sachitbhat"

############
# Timeline #
############

events:
  - image: "/img/timeline/Google.png"
    organization: "Google"
    date: "November 2017 - Present"
    role: "Google Student Innovator: Google Cloud Platform"
    desc1: "Educate Vanderbilt community on Google Cloud Platform applications and services through tech
          talks and smaller sessions"
    desc2: "Gain extensive understanding of GCP products with insight of user needs"
    desc3: "Collabrolate remotely with other student innovators to create new learning strategies and enhance project initiatives"

  - image: "/img/timeline/ON.png"
    organization: "Open Networking Foundation"
    date: "May 2017 - August 2017"
    role: "Software Engineering Intern"
    desc1: "Worked on ONOS, the controller platform for a software-defined network (SDN)"
    desc2: "Implemented unit and integration tests on partioned mapping of ONOS controller"
    desc3: "Optimized cluster communication protocols on ONOS distributed core"
    desc4: "Technoligies utilized: Java, Maven, Buck, Protobuf, JUnit"

  - image: "/img/timeline/vappsupdated.png"
    organization: "VandyApps"
    date: "August 2016 - Present"
    role: "Secretary"
    desc1: "Direct internal logistics, event management, and community outreach for Vanderbilt's largest computer science club"
    desc2: "Attend weekly meetings to teach new technologies and enhance software development skills"
    # desc3: "~Plan fundraising and outreach events for University of Maryland students and local high school students"

  - image: "/img/timeline/vines.png"
    organization: "Vanderbilt Innovation and Entrepreneurship Society"
    date: "December 2016- Present"
    role: "Event Manager"
    desc1: "Manage VINES external programs and general body meetings to foster entrepreneurial spirit within Vanderbilt community"
    desc2: "Budget, plan, and execute developmental programs of innovative endeavors"
    desc3: "Serve on executive board to enhance overall club structure and strategy"
  
  - image: "/img/timeline/isiscropsimple.png"
    organization: "Vanderbilt Institute for Software Integrated Systems"
    date: "December 2016 - May 2017"
    role: "Undergraduate Research Assistant"
    desc1: "Developed crowdsourcing web application analyze user data under guidance of Professor Yeygeniy Vorobeychik"
    desc2: "Modeled experiments using HTML, CSS JavaScript on Meteor Web framework"
    desc3: "Implemented back-end on MongoDB"


# First image of the Career timeline

career-img: "/img/timeline/Vanderbiltstar.png"

############
#  Skills  #
############

skills:
  - software: "Git"
    language: "C++"
  - software: "Google Cloud Platform"
    language: "Java"
  - software: "XCODE"
    language: "ARM Assembly"
  - software: "Software Defined Networking"
    language: "Swift (Working Proficiency)"




###########
# Contact #
###########

email: "sachit.s.bhat@vanderbilt.edu"

##################
# Social Buttons #
##################

social:
  - title: "linkedin"
    url: "https://linkedin.com/in/sachitbhat"
  - title: "github"
    url: "https://github.com/SBhat35"
  - title: "twitter"
    url: "https://twitter.com/da_bhatman"
  - title: "envelope-o"
    url: "mailto: sachit.s.bhat@vanderbilt.edu"


############
# 404 page #
############

404-img: "/img/404error.png"

################################################################################

# Exclusion list from the generated _site

exclude: ["LICENSE", "README", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems: [jekyll-paginate]
