
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://SBhat35.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: #/personal-jekyll-theme

# Google tracking id

google-tracking-id: "UA-111421888-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

# Sections shown in the index page

pages_list:
  About: 'about'
  Timeline: 'timeline'
  Skills: 'skills'
  Contact: 'contact'

#############
# HTML Head #
#############

lang: "en"
author: "Sachit Bhat"
title: "Sachit Bhat"
description: "Personal Website of Sachit Bhat"
keywords: "sachit, bhat, vanderbilt"
favicon: "/img/favicon.ico"

################
# Header layout #
################

# black-favicon: "/img/black-lab-glass.ico"

# background-img: "../img/intro-bg.jpg"


##########
# Header #
##########

black-favicon: ""
me-img: "/img/2016updated.png"

background-type: "color-gradient"   # It can be either image, 3d-lines or color-gradient.

# The following configurations are common for both color-gradient and 3d-lines.

background-color-shuffle: True  # Keep shuffle True to get different background everytime.
background-colors:  # You must add at least 4 colors.
  - color: "5F9EA0"
  - color: "4682B4"
  - color: "B0C4DE"
  - color: "ADD8E6"

  - color: "B0E0E6"
  - color: "87CEFA"
  - color: "87CEEB"
  - color: "6495ED"
  
  - color: "00BFFF"
  - color: "1E90FF"
  - color: "4169E1"
  - color: "0000FF"
  
  - color: "0000CD"
  - color: "00008B"
  - color: "000080"
  - color: "191970"

background-color-trasition-speed: 0.001
background-color-update-interval: 0.001

# 3d-lines configuration

# background-lines-color: "b2ebf2"
# background-particles: 300

# static background image

# background-img: ""


##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: False # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 4
start-delay: 500
delete-delay: 2000
lines: # You can add HTML Tags in the Text
  - text: "Who am I?"
  - text: "Sachit Bhat"
  - text: "Programmer"
  - text: "Innovator"
  - text: "Pianist"
  - text: "Sports Enthusiast"
  - text: "Foodie"

me-img: "https://github.com/SBhat35.png?size=500"

########
# Blog #
########
enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: False
google-plus-share: True
tumblr-share: False
pinterest-share: True
pocket-share: True
vkontakte-share: True


disqus-shortname: "sachitbhat"

syntax-highlight: True


##############################
# Color the browser elements #
##############################

color-browser: "#1000CC"
apple-status-bar-style: "blue"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########


post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: False
google-plus-share: True
tumblr-share: False
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "sachitbhat"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/spidertocat.png"
    organization: "Google"
    date: "November 2017 - Present"
    role: "Google Student Innovator: Google Cloud Platform"
    desc1: "BLah Blah"
    desct: "uyguyg"


  - image: "/img/timeline/spidertocat.png"
    organization: "Open Networking Lab"
    date: "May 2017 - August 2017"
    role: "Software Engineering Intern"
    desc1: "Saving the neighborhood!"
    desc2: "Add stuff sach"




# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "sachit.s.bhat@vanderbilt.edu"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "As an undergraduate studying computer science and economics at Vanderbilt University, I have been exposed to many seemingly disparate topics and concepts, yet
have developed a passion for both cross-disciplinary fields. I love diving into the inner workings of large scale projects and services, and will continue to learn and grow as a thinker."
author_blurb_image: "/img/labtocat.png"

##################
# Social Buttons #
##################

social:
  - title: "linkedin"
    url: "https://linkedin.com/in/in/sachitbhat"
  - title: "twitter"
    url: "https://twitter.com/"
  - title: "github"
    url: "https://github.com/SBhat35"

##########
# Skills #
##########

skills:

  language: "C++"
  language: "Java"
  language: "HTML, CSS, Javascript"
  language: "Swift (Working Proficiency)"
  -software/other: "Git"
  -software/other: "Google Cloud Platform"
  -software/other: "Xcode"
 

  


############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: sachitbhat
keybase-in-social: True
keybase-in-footer: True

################################################################################



# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
